ls source to list current directory, most recent first
zsh-users/zaw pull request #98
Opened 2018-03-28 20:13 UTC by jaromil

Hi there. In case you like it, I find it useful, but adds deps to xclip and awk

ciao

2018-03-30 08:33 UTC, termoshtt requested changes
Thanks PR.

The interface for `xclip` is good idea, and it will be useful for X11 users. It will be better to supports [pbcopy][pbcopy] and [xsel][xsel] as possible.

[pbcopy]: https://developer.apple.com/legacy/library/documentation/Darwin/Reference/ManPages/man1/pbcopy.1.html
[xsel]: https://github.com/kfish/xsel

I have two concerns:

- There is `open-file` source to show the result of `ls`. 
- xclip feature should not be the main action for this source.

I hope you add "copy to clipboard" action for `open-files` source instead of creating new source, and configure it as default using custom action introduced in #96

2018-03-30 08:33 UTC, termoshtt commented on sources/ls.zsh
> +	savealias=`alias ls`
Please use `local` to restrict scope. You should use `command ls` if you concern about alias.

2018-03-30 08:33 UTC, termoshtt commented on sources/ls.zsh
> +function strip-ls-long() {
Please rename to `zaw-src-ls-strip` or some name you prefer to restrict name scope.

2018-03-30 08:33 UTC, termoshtt commented on sources/ls.zsh
> +	BUFFER="$BUFFER `print -- $line | strip-ls-long`"
Please use `$LBUFFER` and `$RBUFFER`

2018-03-31 09:53 UTC, jaromil commented
OK, thanks for your review, all very reasonable.
Give me some time to go over this, I'll likely be able later on by end of april.

2025-02-18 19:08 UTC, jaromil commented
Sorry I never found time for this and meanwhile switched to use bash.

2025-02-18 19:08 UTC, closed without merging